name: e2e tests

on:
  push:
    branches:
      - main
      - playwright-tests
  pull_request:
    branches:
      - main

env:
  WASP_TELEMETRY_DISABLE: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Wasp
        run: curl -sSL https://get.wasp-lang.dev/installer.sh | sh -s

      - name: Docker setup
        uses: docker/setup-buildx-action@v3

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('app/package-lock.json') }}

      # - name: Install Node.js dependencies
      #   run: |
      #     cd app
      #     npm ci

      - name: Setup Dummy Env Vars 
        run: |
          cd app
          cp .env.server.example .env.server

      - name: Install Playwright tests
        run: |
          cd app
          npm install @playwright/test

      - name: Set up Playwright
        run: |
          cd app
          npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd app
          DEBUG=pw:webserver npx playwright test
